sonar.projectKey=miyakona_usako
sonar.organization=miyakona

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=usako
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
sonar.tests=gas/src/test,__tests__,worker/src/__tests__
sonar.test.inclusions=**/*.test.js,**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info,worker/coverage/lcov.info
sonar.coverage.exclusions=**/*.test.js,**/*.test.ts,**/node_modules/**,**/coverage/**,**/jest.config.js,**/babel.config.js,**/index.js,**/.github/**,**/dist/**,main.js,tasks/**,**/tasks/**,**/__mocks__/**,**/.eslintrc.js
sonar.qualitygate.wait=false
sonar.javascript.version=20
sonar.exclusions=**/node_modules/**,**/coverage/**,**/.github/**,**/dist/**,**/lcov-report/**
sonar.cpd.exclusions=**/test/**,**/__tests__/**,**/node_modules/**,**/coverage/**,tasks/**,**/tasks/**
sonar.issuesReport.html.enable=true

# Quality Gate設定
sonar.qualitygate.ignoreSmallChanges=true
sonar.coverage.jacoco.xmlReportPaths=coverage/clover.xml,worker/coverage/clover.xml
